CREATE TABLE author
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP WITH TIME ZONE,
    updated TIMESTAMP WITH TIME ZONE,
    code    VARCHAR(255)                            NOT NULL,
    CONSTRAINT author_pkey PRIMARY KEY (id)
);

CREATE TABLE store
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP WITH TIME ZONE,
    updated TIMESTAMP WITH TIME ZONE,
    name    VARCHAR(255)                            NOT NULL,
    code    VARCHAR(255)                            NOT NULL,
    CONSTRAINT store_pkey PRIMARY KEY (id)
);

CREATE TABLE books
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created   TIMESTAMP WITH TIME ZONE,
    updated   TIMESTAMP WITH TIME ZONE,
    code      VARCHAR(255)                            NOT NULL,
    author_id BIGINT,
    store_id  BIGINT,
    CONSTRAINT book_pkey PRIMARY KEY (id),
    CONSTRAINT book_author_fk FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE,
    CONSTRAINT book_store_fk FOREIGN KEY (store_id) REFERENCES store (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT book_author_store_index UNIQUE (author_id, store_id)
);
